version: "3"
services:
  app:
    container_name: budget-api
    image: node:11.14.0-alpine
    build: ./
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      PORT: 3090
      DEBUG: homebudgetapi:*
      WAIT_HOSTS: mongodb:27017
    ports:
      - 3090:3090

  mongodb:
    image: mongo
    expose:
      - 27017
    volumes:
      - ~/data/db:/data/db
